### PR TITLE
Bump `NFT`

### LINKED ISSUE #650: Bump `NFT`
To:

- `forc 0.40.1`
- `fuel-core 0.18.1`
- `fuels-rs 0.42.0`

### PR DESCRIPTION
**Pull request by K1-R1**
## Type of change

- Improvement (refactoring, restructuring repository, cleaning tech debt, ...)

## Changes

The following changes have been made:

- Bump application to `forc 0.40.1` and `fuel-core 0.18.1`
- Bump test harness to `fuels 0.42.0`

## Related Issues

Closes #650

### CODE REVIEW

**Comment by K1-R1** [comment]
Awaiting release of [Sway multi-token standard](https://github.com/FuelLabs/rfcs/pull/17)

**Comment by Braqzen** [comment]
@K1-R1 Should we close this since the app has been archived for now? Could PR it later? I don't mind either way.

**Comment by K1-R1** [comment]
> @K1-R1 Should we close this since the app has been archived for now? Could PR it later? I don't mind either way.

We're expecting the above standard within the next few bump cycles, then it would be un-archived and bumped to the standard. So it's fine to leave for now

**Comment by bitzoic** [comment]
Closing in favor of https://github.com/FuelLabs/sway-applications/pull/747

**Pull request closed without merging**
