### PR TITLE
Commit_fix

### PR DESCRIPTION
**Pull request by tarunsamanta2k20**
## Type of change

- Bug fix
- New feature
- Improvement (refactoring, restructuring repository, cleaning tech debt, ...)
- Documentation
- Other (describe below)

## Changes

The following changes have been made:

- Change 1
- Change 2

## Notes

- Note 1

## Related Issues

Closes #\<issue number\>

### CODE REVIEW

**Review by Braqzen — APPROVED** [review]
Awesome! LGTM

**Comment by tarunsamanta2k20** [comment]
@Braqzen  please add me as a member of your organization. I want to contribute more in the future.

**Comment by Braqzen** [comment]
> @Braqzen please add me as a member of your organization. I want to contribute more in the future.

Sorry, that's not how that works. You would need to interview for a position.

**Comment by tarunsamanta2k20** [comment]
@Braqzen I am asking for a membership only. i have been working as an open source developer since last year. I have contributed to 50+ organization projects.

**Pull request merged**
