### PR TITLE
New document to track the progress of each app

### LINKED ISSUE #207: New document to track the progress of each app
### Motivation

At the moment there are generally two options for tracking the progress of an application:

1. Check all of the issues and compare it against any PRs / work in master
2. Ask me

This is not ideal for many reasons therefore a new living document should be added which tracks the progress of each application. This allows anyone to glance at a doc and have a good idea of what needs to be done and where the application is at that stage in time.

### PR DESCRIPTION
**Pull request by Braqzen**
## Type of change

- Documentation

## Changes

The following changes have been made:

- Overview
- Commenting on things exclusively in master
  - Exception being some comments for a PR that is just about to go in. Formatter is broken and I rather not do another PR once that goes in
- Added a comment to README

## Related Issues

Closes #207

### CODE REVIEW

**Review by matt-user — COMMENTED** [review]
Would it be possible to have the info for each dapp, game, tutorial inside of a [dropdown](https://gist.github.com/apaskulin/1ad686e42c7165cb9c22f9fe1e389558#dropdowns)?  Imo it would make it easier to navigate.

**Comment by Braqzen** [comment]
> Would it be possible to have the info for each dapp, game, tutorial inside of a [dropdown](https://gist.github.com/apaskulin/1ad686e42c7165cb9c22f9fe1e389558#dropdowns)? Imo it would make it easier to navigate.

For plain markdown, no.
For advanced markdown that uses HTML tags, yes.

I was hoping something like this would exist. It doesn't solve the issue of plain text being a pain to work with and in-fact it will make it worse but that's for us to deal with and not a user. I will look into making these changes soon.

**Review by matt-user — APPROVED** [review]
lgtm!

**Review by nfurfaro — APPROVED** [review]
Looks reasonable to me.

**Review by bitzoic — APPROVED** [review]
lgtm!

**Review by simonr0204 — APPROVED** [review]

**Pull request merged**
