### PR TITLE
Bump ci and contributor book

### PR DESCRIPTION
**Pull request by SwayStar123**
## Type of change

- Other (describe below)
Bumping

## Changes

-Updated rust to latest version
-Updated ci and contributor book toolchain to use latest

### CODE REVIEW

**Review by Braqzen — APPROVED** [review]
I've bumped this recently. Is there a reason to bump this again?

**Review by bitzoic — APPROVED** [review]
Same forc versions?

**Comment by SwayStar123** [comment]
Mainly wanted to bump rust version

**Comment by SwayStar123** [comment]
Nvm too many clippy errors ill do this later lol

**Pull request closed without merging**
