### PR TITLE
Include block manipulation in commented escrow tests

### LINKED ISSUE #220: Finish testing the Escrow
### Motivation

Recently the projects have been bumped to a newer SDK release which supports [block manipulation](https://fuellabs.github.io/fuels-rs/v0.23.0/testing/chains.html). There are a few tests that need to be completed.

Look in `harness.rs` to see if there is a note mentioning which tests must be updated otherwise look through all the functions.

### PR DESCRIPTION
**Pull request by fgimenez**
## Type of change

- Improvement (refactoring, restructuring repository, cleaning tech debt, ...)

## Changes

The wallets provider config is modified to set `manual_blocks_enabled` to true, then all the implemented tests that were ignored because of lack of block manipulation are un-ignored and modified to pass.

## Notes

There are still some tests ignored but unimplemented, let me know if they should be implemented as part of this PR.

## Related Issues

Closes #220

### CODE REVIEW

**Review by Braqzen — COMMENTED** [review]
Yeah, to close the issue it would be great to implement the remaining ignored tests which seem to be

- `takes_payment_in_two_escrows()`
- `withdraws_collateral_in_two_escrows()`

I would also remove the `SDK block manipulation` comment from `harness.rs` as this PR addresses that.

Aside from that things look good :)

**Comment by fgimenez** [comment]
> Yeah, to close the issue it would be great to implement the remaining ignored tests which seem to be
> 
> * `takes_payment_in_two_escrows()`
> * `withdraws_collateral_in_two_escrows()`
> 
> I would also remove the `SDK block manipulation` comment from `harness.rs` as this PR addresses that.

Sure on it :+1: 

> Aside from that things look good :)

awesome thanks!

**Comment by fgimenez** [comment]
ok done, @Braqzen please take another look

**Review by Braqzen — APPROVED** [review]
Cool, LGTM :)

**Pull request merged**
