### PR TITLE
Delete AMM App

### PR DESCRIPTION
**Pull request by SwayStar123**
The original author of the AMM app has left the fuel organization, this plus the fact that the sway code has very little comments, and that the tests are written in an abstract way, makes this app very hard to maintain.

## Type of change

- Other (describe below)
- Deprecation of AMM app

## Changes

The following changes have been made:

- Delete the AMM app directory

### CODE REVIEW

**Comment by Braqzen** [comment]
"I find it difficult to maintain this" is not a valid reason to delete this.

**Comment by SwayStar123** [comment]
@hummusonrails

**Review by hummusonrails — APPROVED** [review]

**Review by Braqzen — CHANGES_REQUESTED** [review]
I haven't blocked anything in a long time but this is unacceptable reasoning and the disregard for the comment is disrespectful.

Blocking until a discussion has been had.

**Comment by K1-R1** [comment]
If bumping the AMM has become a significant blocker, rather than delete I'd advocate that we archive the AMM temporarily as we did the `Fraction-NFT` (#714).  However the intention would then be to reintroduce the AMM at a later date. Perhaps with a refactor of the tests if they have become to difficult to maintain in their current form.
The AMM app is a great example app, especially for the usage of scripts, and I don't think we should delete it.

**Comment by SwayStar123** [comment]
Closed in favour of #769

**Pull request closed without merging**
